[build-system]
requires = ["setuptools>=51", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100
target_version = ['py36', 'py37', 'py38']
skip-string-normalization = true
