name: Diagram

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "docs,.github,.gitignore,.env_example,.readthedocs.yaml,tox.ini,LICENSE"
