name: CI

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools ipython
        python -m pip install 'tox<4'
    - name: Tests
      run: |
        tox -e unit-tests
        tox -e linters
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IBMQ_TOKEN: ${{ secrets.IBMQ_TOKEN }}
        JUPYTERHUB_USER: ${{ secrets.JUPYTERHUB_USER }}
        REFRESH: ${{ secrets.REFRESH }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: ./build/coverage/coverage.xml
        verbose: true
