name: Unit tests

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools ipython
        python -m pip install tox
    - name: Run unit-tests
      run: 
        tox -e unit-tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IBMQ_TOKEN: ${{ secrets.IBMQ_TOKEN }}
        JUPYTERHUB_USER: ${{ secrets.JUPYTERHUB_USER }}
        REFRESH: ${{ secrets.REFRESH }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./build/coverage/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./build/coverage/codecov_report.txt
        verbose: true
